apiVersion: v1
kind: Service              # 1
metadata:
  name: coit-backend1-lb
spec: 
  type: LoadBalancer
  ports:
  - port: 8080               # 3
    protocol: TCP          # 4
    targetPort: 8080       # 5
  selector:                # 6
    app: coit-backend1       # 7
